cluster_es:
  "nodos"       : ["10.33.32.107:9200", "10.33.32.108:9200", "10.33.32.109:9200"]
  "clustername" : "DEV-ECO-6X"

defaults:
  "lapse":       15
  "times_warn":   3
  "times_alert":  4
  "prono_type":  'F'           # formula | "D" Discrete 
  "umbral_type": 'porcentual'  # 'fix' 
  "difiere_segs" : 30
