cluster_es:
  "nodos"       : ["10.33.32.107:9200", "10.33.32.108:9200", "10.33.32.109:9200"]
  "clustername" : "DEV-ECO-6X"

defaults:
  "lapse":       15
  "veces_warn":   3
  "veces_alert":  4
  "prono_type":  'F'  
  "umbral_type": 'porcentual'  # 'fix'
